### ISSUE TITLE
Filenames are too long

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/eth2.0-spec-tests#15]
For example, this filepath is 201 characters.
```
tests/general/phase0/bls/sign_msg/small/sign_msg_0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3_0x0000000000000000000000000000000000000000000000000000000000000000_0x0100000000000000
```

Linux has a maximum filename length of 255 characters for most filesystems. When we ultilize caching in our continuous integration or even locally, the base path may be more than 54 characters. 

Please reduce the filename length for these tests.

**Comment by prestonvanloon** [comment]
Example full local directory with caching enabled ends up being 309 characters. 

```
/home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/external/eth2_spec_tests_general/tests/general/phase0/bls/sign_msg/small/sign_msg_0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3_0x0000000000000000000000000000000000000000000000000000000000000000_0x0100000000000000 
```

**Comment by prestonvanloon** [comment]
For now, we're forking the tar.gz and renaming all of these long directories so we can update to 0.8.3.

**Comment by protolambda** [comment]
Sorry, was a bit careless with those names. Will change it after interop, fully prioritizing bugs + interop over formatting now.

**Comment by prestonvanloon** [comment]
Discussed offline that the culprit seems to be ecryptfs. Nonetheless, a shorter filename would be appreciated.

**Comment by mratsim** [comment]
Yes, so on unix you have 2 constants, one for max filename at 255 characters usually and one for max total path at 4096 characters.

Ecryptfs adds metadata or random hashes of about 100 characters to each file stored in an encrypted partition.

**Comment by protolambda** [comment]
See https://github.com/ethereum/eth2.0-specs/pull/1405

**Comment by prestonvanloon** [comment]
Thanks @protolambda. This is effectively resolved for the next version so i'll close this.
