### ISSUE TITLE
v1.0.0-rc.0 fast_aggregate_verify_infinity_pubkey uses `messages` field instead of `message`

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/eth2.0-spec-tests#21]
It wasn't hard to work around, but I thought it was strange that the `fast_aggregate_verify_infinity_pubkey` test uses a `messages` field instead of `message`. It would be nice for it to be consistent.

Version: v1.0.0-rc.0

**Comment by hwwhww** [comment]
Thanks @michaelsproul 👍
https://github.com/ethereum/eth2.0-specs/pull/2099 fixes this typo.
