### ISSUE TITLE
[Release needed] BLS tests: fast_aggregate_verify inconsistent format v1.0.0-rc0

### ISSUE THREAD

**Issue by mratsim** [ethereum/eth2.0-spec-tests#22]
There is one test in fast_aggregate_verify that has an inconsistent format with the rest (fast_aggregate_verify_infinity_pubkey)

It uses `messages` (plural) instead of `message`

![image](https://user-images.githubusercontent.com/22738317/97201478-cca64b80-17b2-11eb-8bfe-f1792a13e5f6.png)

**Comment by mratsim** [comment]
Fixed by https://github.com/ethereum/eth2.0-specs/pull/2099 but I guess we need a new release for those who uses the tarballs directly.

For now I'll edit manually in my downloaded files

**Comment by hwwhww** [comment]
fixed in v1.0.0 tests.
