### ISSUE TITLE
Operations/attester_slashing success cases issue

### ISSUE THREAD

**Issue by zilm13** [ethereum/eth2.0-spec-tests#4]
Solved in https://github.com/ethereum/eth2.0-specs/pull/1126 but looks like generation was done using `v0.6.2`, so we have exits like `6, 5, 5, 5, 5, 6, 6, 6`. Waiting for regeneration.

**Comment by zilm13** [comment]
+ same for `sanity/blocks`, `attester_slashing` test case

**Comment by protolambda** [comment]
Yes, discovered these just too late for the v0.6.2 release :(
There was a fix, but it was into `dev`, so it didn't make the generation of test-vectors. We're porting it back. See https://github.com/ethereum/eth2.0-specs/pull/1137

**Comment by zilm13** [comment]
Sounds good!

**Comment by protolambda** [comment]
I believe this was fixed in v0.6.3
